name: 5-day-gen-ai
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip=24.2
  - numpy=1.26.3
  - pydantic=2.10.4
  - pyyaml=6.0
  - setuptools=75.1.0
  - wheel=0.44.0
  - transformers=4.47.1 
  - datasets=3.2.0
  - scikit-learn=1.6.0
  - python-json-logger=2.0.7
  - python-dotenv=1.0.1
  - tenacity=9.0.0
  - psycopg2=2.9.9
  - ipykernel=6.29.5
  - google-generativeai=0.8.3
  - kaggle=1.6.17 
  - ipywidgets=8.1.5 
  - grpcio=1.67.1 
  - chromadb=0.6.1 
  - pip:
    - torch==2.5.1
    - torchvision==0.20.1
